version: '3'

services:
  ui:
    container_name: ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - API_URL=${API_URL}
      - PORT=${PORT}